from collections import Counter

from app.clients.github_client import GitHubClient
from app.graph.state import ReviewGraphState


AI_REVIEW_MARKER = "<!-- ai-code-review-governance -->"


def format_github_review_comment(state: ReviewGraphState) -> str:
    """
    Convert workflow state into a GitHub PR comment.
    """

    review_input = state["review_input"]
    all_findings = state.get("all_findings", [])
    verdict = state.get("verdict")
    triage_summary = state.get("triage_summary", {})
    errors = state.get("errors", [])

    severity_counts = Counter(
        finding.severity.value
        for finding in all_findings
    )

    lines = [
        AI_REVIEW_MARKER,
        "",
        "## AI Code Review Result",
        "",
        f"**Repository:** `{review_input.repo_full_name}`",
        f"**PR:** `#{review_input.pr_number}`",
        f"**Title:** {review_input.title}",
        f"**Verdict:** `{verdict.value if verdict else 'UNKNOWN'}`",
        "",
        "### Triage",
        "",
        f"- Files reviewed: `{triage_summary.get('total_files', 0)}`",
        f"- Diff chunks: `{triage_summary.get('total_chunks', 0)}`",
        f"- File types: `{triage_summary.get('file_type_counts', {})}`",
        "",
        "### Findings Summary",
        "",
        f"- Total findings: `{len(all_findings)}`",
        f"- Severity counts: `{dict(severity_counts)}`",
        "",
    ]

    if all_findings:
        lines.extend(
            [
                "### Top Findings",
                "",
                "| Severity | Source | File | Line | Title |",
                "|---|---|---|---|---|",
            ]
        )

        for finding in all_findings[:10]:
            lines.append(
                "| "
                f"{finding.severity.value} | "
                f"{finding.source_type.value} | "
                f"`{finding.file_path}` | "
                f"{finding.line_number or ''} | "
                f"{finding.title} |"
            )

        lines.append("")

        lines.append("### Recommended Actions")
        lines.append("")

        for finding in all_findings[:5]:
            if finding.recommendation:
                lines.append(
                    f"- **{finding.title}:** {finding.recommendation}"
                )

    else:
        lines.extend(
            [
                "### Result",
                "",
                "No findings were detected.",
            ]
        )

    if errors:
        lines.extend(
            [
                "",
                "### Workflow Errors",
                "",
            ]
        )

        for error in errors:
            lines.append(f"- {error}")

    lines.extend(
        [
            "",
            "---",
            "_Generated by AI Code Review & Governance System_",
        ]
    )

    return "\n".join(lines)


async def publish_review_to_github(
    state: ReviewGraphState,
    github_client: GitHubClient | None = None,
) -> dict:
    """
    Publish the review result back to GitHub.

    If an existing AI review comment exists, update it.
    Otherwise create a new comment.
    """

    review_input = state["review_input"]
    client = github_client or GitHubClient()

    body = format_github_review_comment(state)

    comments = await client.list_issue_comments(
        repo_full_name=review_input.repo_full_name,
        pr_number=review_input.pr_number,
    )

    existing_comment = None

    for comment in comments:
        if AI_REVIEW_MARKER in comment.get("body", ""):
            existing_comment = comment
            break

    if existing_comment:
        return await client.update_issue_comment(
            repo_full_name=review_input.repo_full_name,
            comment_id=existing_comment["id"],
            body=body,
        )

    return await client.create_issue_comment(
        repo_full_name=review_input.repo_full_name,
        pr_number=review_input.pr_number,
        body=body,
    )