from app.schemas.review import (
    DiffChunk,
    ReviewFileInput,
    ReviewInput,
)
from app.services import (
    deterministic_review_service
    as run_deterministic_review_for_input,
)
from app.schemas.findings import Finding
from app.schemas.findings import ToolResult




def fake_tool_result(
    tool_name: str,
) -> ToolResult:
    return ToolResult(
        tool_name=tool_name,
        success=True,
        exit_code=0,
        stdout="",
        stderr="",
        raw_output="",
        findings=[
            Finding(
                file_path="app/example.py",
                line_number=1,
                severity="LOW",
                category="quality",
                title=f"{tool_name} test finding",
                description=(
                    f"Test finding generated by "
                    f"{tool_name}."
                ),
                recommendation=(
                    "Review the identified issue."
                ),
                source_type="DETERMINISTIC",
                tool_name=tool_name,
                confidence=1.0,
            )
        ],
    )

def test_run_deterministic_review_combines_findings(
    monkeypatch,
):
    monkeypatch.setattr(
        run_deterministic_review_for_input,
        "run_ruff",
        lambda target_path: fake_tool_result(
            "ruff"
        ),
    )

    monkeypatch.setattr(
        run_deterministic_review_for_input,
        "run_mypy",
        lambda target_path: fake_tool_result(
            "mypy"
        ),
    )

    monkeypatch.setattr(
        run_deterministic_review_for_input,
        "run_bandit",
        lambda target_path: fake_tool_result(
            "bandit"
        ),
    )

    review_input = ReviewInput(
        repo_full_name="demo/repo",
        pr_number=1,
        title="Test deterministic review",
        author="chetan",
        commit_sha="abc123",
        files=[
            ReviewFileInput(
                filename=(
                    "app/services/"
                    "deterministic_review_service.py"
                ),
                file_type="source",
                status="modified",
                additions=1,
                deletions=0,
                chunks=[
                    DiffChunk(
                        file_path=(
                            "app/services/"
                            "deterministic_review_service.py"
                        ),
                        chunk_index=0,
                        start_line=1,
                        end_line=1,
                        content="+ test = True",
                    )
                ],
            )
        ],
    )

    tool_results, findings = (
        run_deterministic_review_for_input
        .run_deterministic_review_for_input(
            review_input
        )
    )

    assert len(tool_results) == 3

    tool_names = {
        result.tool_name
        for result in tool_results
    }

    assert tool_names == {
        "ruff",
        "mypy",
        "bandit",
    }

    assert len(findings) == 3